---
title: "Advent of Code 2015 - Day 3"
author: "Gus Lipkin"
output: html_notebook
---

```{r}
library(tidyverse)
library(stringr)
```

```{r}
# part 1
dt <- readLines("input.txt")

dirX <- function(x) {
  case_when(
    x == "^" ~ 0,
    x == ">" ~ 1,
    x == "<" ~ -1,
    x == "v" ~ 0
  )
}
dirY <- function(x) {
  case_when(
    x == "^" ~ 1,
    x == ">" ~ 0,
    x == "<" ~ 0,
    x == "v" ~ -1
  )
}

df <- data.frame("x" = 0, "y" = 0)
for(i in 1:nchar(dt))
  df <- rbind(df, data.frame("x" = dirX(substr(dt, i, i)),
                             "y" = dirY(substr(dt, i, i))))
dt <- data.table::data.table(df)
dt$cumX <- cumsum(dt$x)
dt$cumY <- cumsum(dt$y)
dt <- dt[, .(cumX, cumY)]
nrow(unique(dt))
```

```{r}
# part 2
dt <- readLines("input.txt")

dirX <- function(x) {
  case_when(
    x == "^" ~ 0,
    x == ">" ~ 1,
    x == "<" ~ -1,
    x == "v" ~ 0
  )
}
dirY <- function(x) {
  case_when(
    x == "^" ~ 1,
    x == ">" ~ 0,
    x == "<" ~ 0,
    x == "v" ~ -1
  )
}

dfR <- data.frame("x" = 0, "y" = 0)
dfS <- data.frame("x" = 0, "y" = 0)
for(i in seq(1, nchar(dt), 2))
  dfS <- rbind(dfS, data.frame("x" = dirX(substr(dt, i, i)),
                               "y" = dirY(substr(dt, i, i))))
for(i in seq(2, nchar(dt), 2))
  dfR <- rbind(dfR, data.frame("x" = dirX(substr(dt, i, i)),
                               "y" = dirY(substr(dt, i, i))))

dts <- data.table::data.table(dfS)
dts$cumX <- cumsum(dts$x)
dts$cumY <- cumsum(dts$y)
dtr <- data.table::data.table(dfR)
dtr$cumX <- cumsum(dtr$x)
dtr$cumY <- cumsum(dtr$y)

dt <- data.table::data.table(rbind(dts, dtr))

dt <- dt[, .(cumX, cumY)]
nrow(unique(dt))
```

