---
title: "18: Duet"
---

```{r}
#| message: false
library(mistlecode)
dt <- readLines("input.txt")
```

## Part 1

Last bit of dumb stuff with `self$try_numeric()` but it works. I need to add something in to the actual program to fix this...

```{r}
registers <-
  dt |>
  str_extract(" ([a-z]) ") |>
  unique() |>
  str_remove_all(" ") |>
  purrr::discard(is.na) |>
  sort()
registers <- 
  rep(0L, length(registers)) |>
  as.list() |>
  `names<-`(registers)
registers$last_sound <- 0L

functions <- list(
  "snd" = \(x, y) {
    self$last_sound <- self[[x]]
    private$.inc()
  },
  "set" = \(x, y) {
    y <- self$val_or_index(y)
    self[[x]] <- y
    private$.inc()
  },
  "add" = \(x, y) {
    y <- self$val_or_index(y)
    self[[x]] <- self[[x]] + y
    private$.inc()
  },
  "mul" = \(x, y) {
    y <- self$val_or_index(y)
    self[[x]] <- self[[x]] * y
    private$.inc()
  },
  "mod" = \(x, y) {
    y <- self$val_or_index(y)
    self[[x]] <- self[[x]] %% y
    private$.inc()
  },
  "rcv" = \(x, y) {
    if (self[[x]] != 0) {
      print(self$last_sound)
      break
    }
    private$.inc()
  },
  "jgz" = \(x, y) {
    if (self[[x]] > 0) private$.inc(y) else private$.inc()
  }
)

create_assembly(registers, functions)$run(dt)
```

