---
title: "2022-12: Hill Climbing Algorithm"
format: html
eval: false
---

```{r}
#| message: false
library(mistlecode)
```

```{r}
mat <- 
  readLines("input2.txt") |>
  stringr::str_split("", simplify = TRUE)
```

```{r}
adjacent <- function(point, mat) {
  y <- point[1]; x <- point[2];
  tibble::tibble(
    'y' = c(y-1, y+1, y,   y),
    'x' = c(x,   x,   x-1, x+1)
  ) |>
    dplyr::filter(
      dplyr::between(.data$y, 1, nrow(mat)),
      dplyr::between(.data$x, 1, ncol(mat))
    ) |>
    purrr::pmap(\(y, x) {
      c(y, x)
    })
}

hash <- function(x) paste0(x, collapse = ' ')
```


```{r}
find_path <- function(mat, current, end, neighbors = adjacent, cost = function(x, y) dist(rbind(x, y), method = 'manhattan')[1]) {

  open_list <- collections::priority_queue()$clear()$push(current, 0)
  g_score <- matrix(Inf, nrow = nrow(mat), ncol = ncol(mat))
  f_score <- matrix(Inf, nrow = nrow(mat), ncol = ncol(mat))
  g_score[current[1], current[2]] <- 0
  f_score[current[1], current[2]] <- dist(rbind(current, end), method = 'manhattan')[1]

  came_from <- list()

  while (open_list$size() > 0) {
    current_node <- open_list$pop()
    if (all(current_node == end)) {
      path <- list()
      node <- current_node
      while (!is.null(came_from[[hash(node)]])) {
        path <- append(path, list(node))
        node <- came_from[[hash(node)]]
      }
      path <-
        path |>
        append(list(current)) |>
        rev()
      return(list('path' = path[-1], 'cost' = g_score[end[1], end[2]]))
    }
    for (neighbor in neighbors(current_node, mat)) {
      move_cost <- cost(current_node, neighbor, mat)
      if (is.na(move_cost) || move_cost == Inf) next
      tentative_g_score <- g_score[current_node[1], current_node[2]] + move_cost
      if (tentative_g_score < g_score[neighbor[1], neighbor[2]]) {
        came_from[[hash(neighbor)]] <- current_node
        g_score[neighbor[1], neighbor[2]] <- tentative_g_score
        f_score[neighbor[1], neighbor[2]] <- tentative_g_score + dist(rbind(neighbor, end), method = 'manhattan')[1]
        open_list$push(neighbor, -f_score[neighbor[1], neighbor[2]])
      }
    }
  }
  return(NULL)
}

mat |>
  apply(c(1, 2), \(x) {
    if (x == tolower(x)) which(letters == x) else if (x == 'E') 27 else 0
  }) |>
  as.integer() |>
  `dim<-`(dim(mat)) |>
  find_path(which(mat == 'S', arr.ind = TRUE)[1,], which(mat == 'E', arr.ind = TRUE)[1,], cost = \(x, y, mat) {
    x <- mat[x[1], x[2]]; y <- mat[y[1], y[2]];
    if ((y - x) > 1) NA else (y - x)
  }) |>
  purrr::pluck('path') |>
  (\(x) { print(length(x)); x; })() |>
  unlist () |>
  matrix(ncol = 2, byrow = TRUE) |>
  tibble::as_tibble() |>
  setNames(c('row', 'col')) |>
  dplyr::mutate('rowId' = dplyr::row_number()) |>
  ggplot2::ggplot(ggplot2::aes(x = col, y = -row)) +
  ggplot2::geom_point(ggplot2::aes(color = rowId), size = 5, shape = 15)
  # ggplot2::geom_text(ggplot2::aes(label = rowId))
```

440
441
436
437

```{r}

```

