---
title: "2022-11: Monkey in the Middle"
format: html
---

```{r}
#| message: false
library(mistlecode)
```

```{r}
dt <- readLines("input.txt")

dt <- 
  data.frame(dt) |>
  mutate(monkey = cumsum(grepl("Monkey \\d+:", dt)) - 1) |>
  filter(dt != "")
```

Oh no. I'm going to bed.

## Part 1

This was so much fun! I dipped my toes into S3 classes, made a useful function
factory, and did some recursion. I had a bit of trouble making sure my list of
monkeys was getting passed around properly and returned because loops can't
change objects in the global environment. That said, I have a bad feeling about
part 2.

```{r}
operation <- function(op, val) {
  function(old) {
    if (val == "old") { val <- as.integer(old) } 
    else { val <- as.integer(val) }
    
    if (op == "*") { val <- old * val }
    else if (op == "+") { val <- old + val }
    
    return(val)
  }
}

new_monkey <- function(dt, x) {
  name <- str_extract(dt[1,"dt"], "\\d+")
  starting_items <- 
    str_split(dt[2,"dt"], ":|,", simplify = TRUE)[1,-1] |> as.integer()
  opp <- 
    str_split(dt[3, "dt"], "=", simplify = TRUE)[1,2] |>
    str_match(" (new|old) (\\+|\\-|\\*|\\/) (old|\\d+)")
  op <- operation(op = opp[1,3], val = opp[1,4])
  test <- str_extract(dt[4,"dt"], "\\d+") |> as.integer()
  case_true <- str_extract(dt[5,"dt"], "\\d+")
  case_false <- str_extract(dt[6,"dt"], "\\d+")
  x <- list(
    "name" = name,
    "starting_items" = starting_items,
    "operation" = op,
    "test" = test,
    "case_true" = case_true,
    "case_false" = case_false,
    "inspections" = 0
  )
  structure(x, class = "monkey")
}

monkeys <- 
  lapply(unique(dt$monkey), \(m) { 
    new_monkey(dt[dt$monkey == m,], m) 
  })
names(monkeys) <- sapply(monkeys, \(m) m$name)

process_items <- function(item, monkey, these_monkeys) {
  if (is.na(monkey$starting_items[item]) | 
      item > length(monkey$starting_items)) { return(these_monkeys) }
  worry_level <- monkey$operation(monkey$starting_items[item])
  worry_level <- floor(worry_level / divide)
  if (worry_level %% monkey$test == 0) {
    case_true <- these_monkeys[[monkey$case_true]]$starting_items
    case_true <- c(case_true, worry_level)
    case_true <- case_true[!is.na(case_true)]
    these_monkeys[[monkey$case_true]]$starting_items <- case_true
  } else {
    case_false <- these_monkeys[[monkey$case_false]]$starting_items
    case_false <- c(case_false, worry_level)
    case_false <- case_false[!is.na(case_false)]
    these_monkeys[[monkey$case_false]]$starting_items <- case_false
  }
  process_items(item + 1, monkey, these_monkeys)
}

process_monkey <- function(i, these_monkeys) {
  if (i == length(monkeys) + 1) { return(these_monkeys) }
  monkey <- these_monkeys[[i]]
  these_monkeys <- process_items(1, monkey, these_monkeys)
  monkey$inspections <- 
    monkey$inspections + length(monkey$starting_items)
  monkey$starting_items <- NA_integer_
  these_monkeys[[i]] <- monkey
  process_monkey(i + 1, these_monkeys)
}

round <- function(these_monkeys, round) {
  if (round == round_max + 1) { return(these_monkeys) }
  these_monkeys <- process_monkey(1, these_monkeys)
  round(these_monkeys, round + 1)
}
```

```{r}
divide <- 3
round_max <- 20
m <- round(monkeys, 1)
sapply(m, \(m) m$inspections) |>
  sort(decreasing = TRUE) |>
  head(2) |>
  prod()
```

## Part 2

```{r}
process_items <- function(item, monkey, these_monkeys) {
  if (is.na(monkey$starting_items[item]) | 
      item > length(monkey$starting_items)) { return(these_monkeys) }
  a <- monkey$operation(monkey$starting_items[item])
  b <- monkey$test
  s <-
    sapply(c(23, 19, 13, 17), \(b) {
      (1:1000)[sapply(1:1000, \(m) a %% m == b %% m)]
    }) |>
    unlist() |>
    table()
  worry_level <- floor(a / max(which(s == 4)))
  if (worry_level %% monkey$test == 0) {
    case_true <- these_monkeys[[monkey$case_true]]$starting_items
    case_true <- c(case_true, worry_level)
    case_true <- case_true[!is.na(case_true)]
    these_monkeys[[monkey$case_true]]$starting_items <- case_true
  } else {
    case_false <- these_monkeys[[monkey$case_false]]$starting_items
    case_false <- c(case_false, worry_level)
    case_false <- case_false[!is.na(case_false)]
    these_monkeys[[monkey$case_false]]$starting_items <- case_false
  }
  process_items(item + 1, monkey, these_monkeys)
}

divide <- 1
round_max <- 1
i <- 1
m <- monkeys
while (i <= 10000) {
  m <<- round(m, 1)
  i <- i + 1
}
sapply(m, \(m) m$inspections) |>
  sort(decreasing = TRUE) |>
  head(2) |>
  prod()

2500700045 > 2713310158
```

```{r}
a <- 25811
b <- 23
l <- 1000
s1 <- (1:1000)[sapply(1:1000, \(m) a %% m == 23 %% m)]
s2 <- (1:1000)[sapply(1:1000, \(m) a %% m == 19 %% m)]

s <-
  sapply(c(23, 19, 13, 17), \(b) {
    (1:1000)[sapply(1:1000, \(m) a %% m == b %% m)]
  })
names(s) <- c(23, 19, 13, 17)
max(which(table(unlist(s)) == 4))

max(intersect(s1, s2))
```


```{r}
combn(c(23, 19, 13, 17), m = 2) |>
  t() |>
  apply(1, prod)
```
