---
title: "The Sum of Its Parts"
format: html
date: "2018-12-07"
draft: true
eval: false
---

```{r}
edge_pairs <-
  'test.txt' |>
  readLines() |>
  stringr::str_extract_all('( [A-Z] )') |>
  purrr::map(stringr::str_trim)
```


## Part 1

```{r}
# graph <-
graph <- igraph::make_empty_graph() |>
  edge_pairs |>
  purrr::map(\(x) {
    igraph::edge(
      c(x[1], x[2], weight = which(LETTERS == x[2]) - which(LETTERS == x[1]))
    )
  }) |>
  unlist(recursive = FALSE) |>
  igraph::make_graph() |>
  igraph::`edge.attributes<-`()

graph |>
  igraph::all_shortest_paths(from = 'C', )


add_edge <- function(graph = NULL, edges) {
  if (length(edges) == 0) return(graph)
  if (is.null(graph)) {
    graph <-
      edges |>
      unlist() |>
      unique() |>
      length() |>
      igraph::make_empty_graph()
    igraph::V(graph)$name <- edges |> unlist() |> unique()
  }
  graph |>
    igraph::add_edges(edges[[1]], 'weight' = which(LETTERS == edges[[1]][2]) - which(LETTERS == edges[[1]][1])) |>
    add_edge(edges[-1])
}

add_edge(edges = edge_pairs)
```




```{r}
DiagrammeR::mermaid(c("graph LR;",
                      apply(dt[rowSums(is.na(dt)) == 0, ], 1, function(x) {
                        paste0(x["predecessor"], " --> ", x["task"], ";")
                      })))
```

```{r}
start <- unique(p[!(p %in% t)])
end <- unique(t[!(t %in% p)])
vec <- c()
ls <- list()

getParent <- function(x) {
  x <- dt$predecessor[dt$task %in% x]
  if(length(x) > 0) {
    x <- rev(sort(unique(x)))
    ls <<- append(ls, paste(rev(x), collapse = ""))
    vec <<- c(vec, x)
    return(getParent(x))
  } else { return(x) }
}

getParent(end)
lapply(ls, function(x) {
  unique(str_split(x, ""))
}) |>
  rev() |>
  unlist() |>
  unique() -> vec
paste(c(vec, end), collapse = "")
```

KVCSHBXDQMJGFZYROUAPLIEWTN
CKVSHBXDQMJGFZYROUAPLIEWTN
KVCBSHXDJMGQFYRZOAULPIEWTN
KCVBHSDXFGJMQRYZOAULPIEWTN
