---
title: "Advent of Code 2021 - Day 15"
author: "Gus Lipkin ~ github.com/guslipkin/AdventOfCode2021"
output: html_notebook
---

```{r}
library(tidyverse)
library(stringr)
library(data.table)

dt <- readLines("input2.txt")
dt <- str_split(dt, "", simplify = TRUE)
dt <- data.frame(apply(dt, 2, as.numeric))
```

## Part 2

```{r}
dt <- readLines("input2.txt")
dt <- str_split(dt, "", simplify = TRUE)
dtM <- apply(dt, c(1, 2), as.numeric)
dt <- dtM

dt <- dt - 1

mat <- matrix(NA, nrow(dt), ncol(dt))

coords <- 
  expand.grid("row" = seq_len(nrow(mat)), "col" = seq_len(ncol(mat)))

get_adjacent <- function(xx, yy, ncol, nrow) {
  x <- xx; y <- yy
  x <- (x-1):(x+1); y <- (y-1):(y+1)
  
  x <- x[sapply(x, \(j) between(j, 1, ncol))]
  y <- y[sapply(y, \(j) between(j, 1, nrow))]

  expand.grid("col" = x, "row" = y) |>
    filter(!(col == xx & row == yy)) |>
    as.matrix()
}

oldMat <- mat
oldMat[!is.na(oldMat)] <- NA
while (!all(is.na(mat)) & !all(is.na(oldMat)) & all(mat == oldMat)) {
  dt <- dt - 2

mat <- matrix(NA, nrow(dt), ncol(dt))
  which(dt <= 0, arr.ind = TRUE) |>
  data.frame() |>
  arrange(row, col) |>
  apply(1, \(x) {
    mat[x["row"], x["col"]] <<- dtM[x["row"], x["col"]]
  })

mat
  oldMat <- mat
  for (i in 1:nrow(coords)) {
    x <- coords$col[i]
    y <- coords$row[i]
    adj <- get_adjacent(x, y, ncol(mat), nrow(mat))
    
    if (nrow(adj) < 2) {
      mat[adj[, "row"], adj[, "col"]] <<- NA
    }
  }
}
```

```{r warning=FALSE}
# part 1
n <- nrow(dt)
m <- ncol(dt)

sols <- data.frame(matrix(data = -1, nrow = n, ncol = n))
pathX <- c()
pathY <- c()

sols[1, 1] <- 0

for (i in 2:n) {
  sols[i, 1] <- sols[i - 1, 1] + dt[i, 1]
}
for (j in 2:m) {
  sols[1, j] <- sols[1, j - 1] + dt[1, j]
}

for (i in 2:n) {
  for (j in 2:m) {
    if (sols[i - 1, j] < sols[i, j - 1]) {
      sols[i, j] <- sols[i - 1, j] + dt[i, j]
      pathX <- append(pathX, i-1)
      pathY <- append(pathY, j)
    } else {
      sols[i, j] <- sols[i, j - 1] + dt[i, j]
      pathX <- append(pathX, i)
      pathY <- append(pathY, j-1)
    }
  }
}
sols
data.frame("x" = pathX, "y" = pathY) %>%
  ggplot() +
  geom_point(aes(x = x, y = y))

sols[n,m]
# 447
# 440
# 454
# 520
# 513
# 514
# 518
```


```{r}
# part 2
```

